### ISSUE TITLE
Add support for Whole Home Wifi Discs

### ISSUE THREAD

**Issue by jxwolstenholme** [jxwolstenholme/btsmarthub_devicelist#10]
Would be nice to add support for telling which Extender disc devices were connected to in setups where they were present.

If anybody has them, would love for somebody to work this out and submit a PR.

**Comment by goul** [comment]
I’ve a couple of Wi-Fi disks on my smart hub 2, what sort of thing are you after?

**Comment by jxwolstenholme** [comment]
Not really sure as don't have any, but thought it might be useful to be able to report which of the discs that the device is connected to? Is that reported currently from http://router_ip/cgi/cgi_basicMyDevice.js ?

**Comment by goul** [comment]
From what I can see the info is present between cgi_owl.js and cgi_basicMyDevice.js. A little juggling to do though and it might be brittle if BT change stuff around. 

From what I can see through the standard GUI, they report roughly as follows : 

a) Direct connected port eg. Port 2
b) Wifi to hub direct - eg. 5Ghz. or 2.4Ghz
c) Extender disc name - eg. 'Garden Shed Disk'

If I can unpick it, would addition of 2 attributes cover this requirement eg.
  'ConnectionType' - > port|wifi|extender
and 
  'ConnectionDetail' as a string.

So as examples : 
     ConnectionType:wifi ConnectionDetail:5Ghz for a direct to hub wifi in 5Ghz range
     ConnectionType:port ConnectionDetail:3 for something plugged straight into the port on hub
     ConnectionType:extender ConnectionDetail:Garden Shed Disk for something connecting to the disk that covers the shed.

**Comment by jxwolstenholme** [comment]
I like it. If you're up for it then sounds good.

Might want to return the mac address of the extender as well?

Don't worry if you've got no time by the way. I may order a couple in the near future and can have a look into it myself.

**Comment by goul** [comment]
Happy to take a look, there is a lot of info in that other file, possibly signal strength etc too.

**Comment by goul** [comment]
Added a PR https://github.com/jxwolstenholme/btsmarthub_devicelist/pull/13

**Comment by goul** [comment]
Thanks for merging - spotted something that might confuse folks a little in the README.md example.

The example forces smarthub_model to 1 and then asks for include_connections - whilst it should work, none of the additional fields will be added describing connections. Might be worth changing model to :

`
smarthub = BTSmartHub(router_ip='192.168.1.254', smarthub_model=2)
`
