### ISSUE TITLE
Home Assistant BT Smarthub 2 support

### ISSUE THREAD

**Issue by mykp** [jxwolstenholme/btsmarthub_devicelist#11]
I'm not an expert but it seems that the btsmarthub_devicelist list already supports the BT Smarthub 2. Can this be added to home assistant please? I am asking because there is a comment in HA community that using bt_smarthub (connected to a BT Smart Hub 2) for device tracker does not work.

**Comment by jxwolstenholme** [comment]
You’re very welcome to submit a PR for it over at homeassistant. If you’re unable to, let me know and I can look into it for you. I no longer use HA so haven’t kept up to date with their codebase.

**Comment by mykp** [comment]
Thanks for the quick response. There has been an open request for about 10 months in HA. I will follow that up.
Best regards

Sent from my mobile

On 28 Jan 2020, at 23:45, jxwolstenholme <notifications@github.com> wrote:

﻿

You’re very welcome to submit a PR for it over at homeassistant. If you’re unable to, let me know and I can look into it for you. I no longer use HA so haven’t kept up to date with their codebase.

**Comment by leroyshirto** [comment]
I have recently tested this library on my smart hub 2 and can confirm it works as expected. 

@mykp the `bt_smarthub` component in HA needs a few tweaks to make it compatible with v0.2.0 of this library. I have created [this](https://github.com/leroyshirto/home-assistant/tree/update-btsmarthub_devicelist-package) feature branch with said changes. Testing it on my local dev instance of HA seems to work. I will try to raise a PR to get this merged upstream. This would be my first PR into HA so I am not sure how long it will take.

**Comment by jxwolstenholme** [comment]
Well done @leroyshirto - looks good.

One thing you might want to do is allow for a CONF to be set explicitly for Smarthub 1/2 support in people's yaml.

Otherwise - this is something I should have done ages ago and huge thanks for making the effort!

**Comment by leroyshirto** [comment]
Thanks. I did think about the adding the config option but I am not too sure how to define custom configuration on components. I'll have a read and see if I can work it out.

**Comment by mykp** [comment]
Thanks very much!

Sent from my mobile

On 29 Jan 2020, at 23:47, Leroy Shirto <notifications@github.com> wrote:

﻿

I have recently tested this library on my smart hub 2 and can confirm it works as expected.

@mykp<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmykp&data=02%7C01%7C%7C7cb305622bda4290857b08d7a50d35e0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637159348460421122&sdata=aFLW6IwoPZgIQqn2PszDEQyVDUZU6yLZMwWdEwu6doE%3D&reserved=0> the bt_smarthub component in HA needs a few tweaks to make it compatible with v0.2.0 of this library. I have created this<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fleroyshirto%2Fhome-assistant%2Ftree%2Fupdate-btsmarthub_devicelist-package&data=02%7C01%7C%7C7cb305622bda4290857b08d7a50d35e0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637159348460421122&sdata=Bwwfq4ZE7jYks5X9cFvW0MYpUJSQiMEZaSztCVqG5k0%3D&reserved=0> feature branch with said changes. Testing it on my local dev instance of HA seems to work. I will try to raise a PR to get this merged upstream. This would be my first PR into HA so I am not sure how long it will take.

**Comment by jxwolstenholme** [comment]
Quick one @leroyshirto - might it be better to initialize the BTSmartHub up in the __init__ so that 
`self.smarthub = BTSmartHub(router_ip=self.host)`
Then you can call 
`data = self.smarthub.get_devicelist(only_active_devices=True)`
in the `get_bt_smarthub_data()` function

Might be talking bollocks though - spent a while away from Python

**Comment by leroyshirto** [comment]
yes that sounds like a good change to make.

**Comment by jxwolstenholme** [comment]
Okay, if you make that change then I might be able to speed up the PR at HA by giving pre-approval.

**Comment by leroyshirto** [comment]
For anyone who is tracking this issue. It should be resolved when this PR is merged and released https://github.com/home-assistant/home-assistant/pull/31292
