### ISSUE TITLE
403 response after BT Smart Hub 2 FW update. Referer header required with requests

### ISSUE THREAD

**Issue by jordan875** [jxwolstenholme/btsmarthub_devicelist#15]
I have been using this for device tracking in Home Assistant but it recently stopped working.

After a recent firmware update on my Smart Hub 2, I get 403 responses when getting the device list:

`Invalid response from Smart Hub: <Response [403]>
Traceback (most recent call last):
  File "/Users/****/btsmarthub_devicelist/run.py", line 3, in <module>
    device_list = smarthub.get_devicelist(
  File "/Users/****/btsmarthub_devicelist/btsmarthub_devicelist/__init__.py", line 60, in get_devicelist
    devicelist = self.get_devicelist_smarthub_2(only_active_devices=only_active_devices,
  File "/Users/****/btsmarthub_devicelist/btsmarthub_devicelist/__init__.py", line 362, in get_devicelist_smarthub_2
    body = self.get_body_content(device_request_url)
  File "/Users/****/btsmarthub_devicelist/btsmarthub_devicelist/__init__.py", line 237, in get_body_content
    body = body.replace("\n", "")
UnboundLocalError: local variable 'body' referenced before assignment`

The firmware update results in 403 when requesting http://192.168.1.254/cgi/cgi_basicMyDevice.js or http://192.168.1.254/cgi/cgi_owl.js. This can be avoided by sending the following header with the request:

{'Referer': 'http://192.168.1.254/basic_-_my_devices.htm' }

I know this is not very widely used but it was working flawlessly for me and I found it very useful. I would love to have it working again!

**Comment by Jordandev678** [comment]
Confirmed, same thing here.

Patch is to just replace the request line for the smarthub 2 device list
```
            response = requests.get(request_url)
```
with 
```
            headers = {"Referer": "http://" + self.router_ip + "/basic_-_my_devices.htm"}
            response = requests.get(request_url, headers=headers)
```

Works for me now. I can submit a PR if you care, but it seemed unnecessary for a one line change.

**Comment by DeanK2022** [comment]
Jordandev678 please do submit the PR, I bet there are quite a few of us scratching our heads over this.

**Comment by DeanK2022** [comment]
Any idea how I can get access to the /Users/****/btsmarthub_devicelist/btsmarthub_devicelist folder?
For the last hour I have tried regular Terminal, gained access to the docker file structure with
docker exec -it $(docker ps -f name=homeassistant -q) bash
but still cannot find this path.
Is there some useful guide on how to get access to HA source code on the Pi, please?  I have a bog standard install (imaged through Balena Etcher and kept up to date).

**Comment by jxwolstenholme** [comment]
Have merged in @typhoon2099's PR - hopefully that fixes all of your issues - I don't have a BT hub anymore and haven't for quite a while so let me know if it doesn't work

**Comment by typhoon2099** [comment]
Thanks for the merge, and thanks for releasing a new version! I'd be happy to take over the maintenance of the PyPi package and the Home Assistant integration if you'd like. I know what it's like trying to support something you no longer have/need.

**Comment by DeanK2022** [comment]
Thank you both, jxwolstenholme and typhoon2099!  Much appreciated.
