### ISSUE TITLE
BT Smarthub Device List v.0.2.2 install

### ISSUE THREAD

**Issue by flaskett** [jxwolstenholme/btsmarthub_devicelist#19]
How do I install this?
Novice needing help

**Comment by typhoon2099** [comment]
Hello, what do you mean by "install this"? Are you trying to use the library in an application you're developing?

**Comment by typhoon2099** [comment]
Closing due to lack of response.

**Comment by wastedwrath** [comment]
I think they were asking how to get this into HomeAssistant which I am also running into issues doing. Any idea on how to do this, have been trying to add it as a customcomponent but no luck.

**Comment by typhoon2099** [comment]
There's no need to add it as a custom component, just follow the installation instructions: https://www.home-assistant.io/integrations/bt_smarthub/

**Comment by wastedwrath** [comment]
> There's no need to add it as a custom component, just follow the installation instructions: https://www.home-assistant.io/integrations/bt_smarthub/

Right OK then, I did that but mine still isn't show unusually, will have to investigate further into logs. Thanks.
