### ISSUE TITLE
Not generating valid JSON

### ISSUE THREAD

**Issue by dfthe1** [jxwolstenholme/btsmarthub_devicelist#26]
The code works great, but the output needs some tweaking in order to be valid JSON:

-- the conversion of single quote marks to double quote marks doesn't seem to be working as the output contains only single quote marks

-- the boolean TRUE/FALSE values are not enclosed in quote marks at all

-- there are a number of carriage returns/line feeds with no obvious reason (not sure if this actually affects the validity of the JSON

I'm using the provided sample code and have  Home Hub 2.

**Comment by typhoon2099** [comment]
The sample code in the README prints out Python's data, which is a list of dictionaries. If you need JSON as output you will need to `import json` at the top of your script and then use `json.dumps` to  create a JSON object. I haven't done this myself (I don't use Python very much), but there's an example over on [W3Schools](https://www.w3schools.com/python/trypython.asp?filename=demo_json_from_python).
